---
- name: Set up Synapse dependencies
  hosts: synapse
  remote_user: root

  tasks:
    - name: Create synapse user and home directory
      ansible.builtin.user:
        name: synapse
        shell: /bin/bash
      register: synapse_user

    - name: Set synapse install directory
      ansible.builtin.set_fact:
        synapse_dir: "{{ synapse_user.home }}/synapse"

    - name: Install required packages
      ansible.builtin.package:
        name:
          - python3
          - python3-apt
          - python3-dev
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
          - build-essential
          - libffi-dev
          - libssl-dev
          - libjpeg-dev
          - libxslt1-dev
          - libpq-dev

- name: Install database
  hosts: synapse
  remote_user: root
  roles:
    - database

- name: Install Synapse in virtual environment
  hosts: synapse
  remote_user: root
  become: yes
  become_user: synapse
  roles:
    - synapse

- name: Install nginx
  hosts: synapse
  remote_user: root
  roles:
    - nginx
