---
- name: Upload existing config files and secrets
  ansible.builtin.copy:
    src: "{{ item.local_path }}"
    dest: "{{ synapse_dir }}/{{ item.dest_name }}"
    owner: synapse
    group: synapse
    mode: 0660
  loop:
    - local_path: "{{ synapse_existing_config_path }}"
      dest_name: "{{ synapse_config_file }}"
    - local_path: "{{ synapse_existing_log_config_path }}"
      dest_name: "{{ synapse_server_name }}.log.config"
    - local_path: "{{ synapse_existing_signing_key_path }}"
      dest_name: "{{ synapse_server_name }}.signing.key"
